name: Build App Automatico

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar codigo
      uses: actions/checkout@v3

    - name: Instalar Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: |
        npm install

    - name: Gerar App
      run: |
        echo "IA construindo aplicativo..."
        
